# Generated by Django 4.0.3 on 2022-04-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_model', models.CharField(max_length=200)),
                ('cars_luxury_type', models.CharField(max_length=200)),
                ('cars_company_name', models.CharField(max_length=200)),
                ('cars_route_name', models.CharField(max_length=200)),
                ('cars_plate_no', models.CharField(max_length=200)),
                ('cars_date_of_journey', models.DateField()),
                ('cars_departure_time', models.TimeField()),
                ('cars_destination_time', models.TimeField()),
                ('cars_created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
