# Generated by Django 4.0.3 on 2022-04-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0003_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies_name', models.CharField(max_length=200)),
                ('companies_contact', models.IntegerField()),
                ('companies_office', models.CharField(max_length=200)),
                ('routes_created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
