# Generated by Django 4.0.3 on 2022-04-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msafiri', '0005_rename_routes_created_time_companies_companies_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions_name', models.CharField(max_length=50)),
                ('regions_created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
